apiVersion: v1
kind: Service
metadata:
  name: pizza
spec:
  selector:
    app: pizza
  type: LoadBalancer
  ports:
    - port: 8000
      targetPort: 8000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pizza
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pizza
  template:
    metadata:          
      labels:
        app: pizza
    spec:              
      containers:
        - name: pizza
          image: pizza-web:latest
          ports:
            - containerPort: 8000
          imagePullPolicy: Never