# Generated by Django 5.2.4 on 2025-08-23 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_pizza_images_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='applied_coupon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='discount_amount',
            field=models.FloatField(default=0),
        ),
    ]
